language: go
cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg/mod
    - $GOPATH/src/github.com/picfight
    - $GOPATH/src/github.com/golang
    - $GOPATH/src/gopkg.in/alecthomas
go:
  - "1.12.x"
sudo: false
before_install:
  - chmod +x ./pfcd_checkout.sh
  - chmod +x ./gotest.sh
install:
  - export PATH=$PATH:$PWD/linux-amd64/
  - mkdir -p $GOPATH/src/github.com/picfight/
  - rm -r -f $GOPATH/src/github.com/picfight/
  - mkdir -p $GOPATH/src/github.com/picfight/pfcd
  - cd $GOPATH/src/
  - pushd $GOPATH/src/github.com/picfight/pfcd
  - $GOPATH/src/github.com/picfight/pfcneutrino/pfcd_checkout.sh
  - go install . ./cmd/...
  - popd
env:
  matrix:
    - RACE=false
    - RACE=true
script:
  - export GO111MODULE=on
  - export PATH=$PATH:$GOPATH/bin
  - ./gotest.sh
