language: go
cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg/mod
    - $GOPATH/src/github.com/picfight
    - $GOPATH/src/github.com/golang
    - $GOPATH/src/gopkg.in/alecthomas
go:
  - "1.12.x"
sudo: false
before_install:
  - chmod +x ./pfcd_checkout.sh
  - chmod +x ./gotest.sh
install:
  - export PATH=$PATH:$PWD/linux-amd64/
  - export GO111MODULE=on
  - go build ./...
  - go install . ./cmd/...
env:
  matrix:
    - RACE=false
    - RACE=true
script:
  - export GO111MODULE=on
  - export PATH=$PATH:$GOPATH/bin
  - ./gotest.sh
